#ifndef TO_LOWER_H
#define TO_LOWER_H
#include "../../s21_string.h"
const char *input_string[] = {"hello",
                              "world",
                              "123abc",
                              "TeSt",
                              "",
                              "Already UPPER",
                              "lowercase",
                              "MIXEDcase",
                              "NUM123",
                              "symbol$#",
                              "short",
                              "LONGERSTRING",
                              "uPpErLoWeR",
                              "123456",
                              "special@char",
                              "abcdefg",
                              "ABCDEFG",
                              "zYXWvUt",
                              "numbers123",
                              "with spaces",
                              "ALLCAPS",
                              "camelCase",
                              "snake_case",
                              "dash-case",
                              "dot.case",
                              "helloWORLD",
                              "function",
                              "test123test",
                              "endline\n",
                              "tabs\t",
                              "newline\ncharacter",
                              "carriage\rreturn",
                              "space ",
                              "   trim",
                              "quotes\"test\"",
                              "apostrophe'test'",
                              "brackets(test)",
                              "percent%100",
                              "underscore_test",
                              "kebab-case",
                              "dot.case.again",
                              "extra-long-string-to-check",
                              "UPPER lower",
                              "multiple words",
                              "sentence case",
                              "123ABC123",
                              "l0w3r",
                              "whitespace     ",
                              "MixedCASE123",
                              "edgeCASE!"};

const char *output_string[] = {"hello",
                               "world",
                               "123abc",
                               "test",
                               "",
                               "already upper",
                               "lowercase",
                               "mixedcase",
                               "num123",
                               "symbol$#",
                               "short",
                               "longerstring",
                               "upperlower",
                               "123456",
                               "special@char",
                               "abcdefg",
                               "abcdefg",
                               "zyxwvut",
                               "numbers123",
                               "with spaces",
                               "allcaps",
                               "camelcase",
                               "snake_case",
                               "dash-case",
                               "dot.case",
                               "helloworld",
                               "function",
                               "test123test",
                               "endline\n",
                               "tabs\t",
                               "newline\ncharacter",
                               "carriage\rreturn",
                               "space ",
                               "   trim",
                               "quotes\"test\"",
                               "apostrophe'test'",
                               "brackets(test)",
                               "percent%100",
                               "underscore_test",
                               "kebab-case",
                               "dot.case.again",
                               "extra-long-string-to-check",
                               "upper lower",
                               "multiple words",
                               "sentence case",
                               "123abc123",
                               "l0w3r",
                               "whitespace     ",
                               "mixedcase123",
                               "edgecase!"};

const s21_size_t count_strings = sizeof(input_string) / sizeof(input_string[0]);
s21_size_t test_num = 0;

#endif