#ifndef TO_UPPER_H
#define TO_UPPER_H
#include "../../s21_string.h"
const char *input_string[] = {"hello",
                              "world",
                              "123abc",
                              "TeSt",
                              "",
                              "Already UPPER",
                              "lowercase",
                              "MIXEDcase",
                              "NUM123",
                              "symbol$#",
                              "short",
                              "LONGERSTRING",
                              "uPpErLoWeR",
                              "123456",
                              "special@char",
                              "abcdefg",
                              "ABCDEFG",
                              "zYXWvUt",
                              "numbers123",
                              "with spaces",
                              "ALLCAPS",
                              "camelCase",
                              "snake_case",
                              "dash-case",
                              "dot.case",
                              "helloWORLD",
                              "function",
                              "test123test",
                              "endline\n",
                              "tabs\t",
                              "newline\ncharacter",
                              "carriage\rreturn",
                              "space ",
                              "   trim",
                              "quotes\"test\"",
                              "apostrophe'test'",
                              "brackets(test)",
                              "percent%100",
                              "underscore_test",
                              "kebab-case",
                              "dot.case.again",
                              "extra-long-string-to-check",
                              "UPPER lower",
                              "multiple words",
                              "sentence case",
                              "123ABC123",
                              "l0w3r",
                              "whitespace     ",
                              "MixedCASE123",
                              "edgeCASE!"};

const char *output_string[] = {"HELLO",
                               "WORLD",
                               "123ABC",
                               "TEST",
                               "",
                               "ALREADY UPPER",
                               "LOWERCASE",
                               "MIXEDCASE",
                               "NUM123",
                               "SYMBOL$#",
                               "SHORT",
                               "LONGERSTRING",
                               "UPPERLOWER",
                               "123456",
                               "SPECIAL@CHAR",
                               "ABCDEFG",
                               "ABCDEFG",
                               "ZYXWVUT",
                               "NUMBERS123",
                               "WITH SPACES",
                               "ALLCAPS",
                               "CAMELCASE",
                               "SNAKE_CASE",
                               "DASH-CASE",
                               "DOT.CASE",
                               "HELLOWORLD",
                               "FUNCTION",
                               "TEST123TEST",
                               "ENDLINE\n",
                               "TABS\t",
                               "NEWLINE\nCHARACTER",
                               "CARRIAGE\rRETURN",
                               "SPACE ",
                               "   TRIM",
                               "QUOTES\"TEST\"",
                               "APOSTROPHE'TEST'",
                               "BRACKETS(TEST)",
                               "PERCENT%100",
                               "UNDERSCORE_TEST",
                               "KEBAB-CASE",
                               "DOT.CASE.AGAIN",
                               "EXTRA-LONG-STRING-TO-CHECK",
                               "UPPER LOWER",
                               "MULTIPLE WORDS",
                               "SENTENCE CASE",
                               "123ABC123",
                               "L0W3R",
                               "WHITESPACE     ",
                               "MIXEDCASE123",
                               "EDGECASE!"};

const s21_size_t count_strings = sizeof(input_string) / sizeof(input_string[0]);
s21_size_t test_num = 0;

#endif